name = "ai-marketplace"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm install && npm run build"
publish = "frontend/build"

pages_build_output_dir = "frontend/build"

# Routes for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { REACT_APP_API_URL = "https://marketplace-api.eba-hekvtpzv.us-east-2.elasticbeanstalk.com" }