name = "ai-marketplace"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm install && npm run build"
publish = "frontend/build"

pages_build_output_dir = "frontend/build"

# Handle root path
[[redirects]]
from = "/"
to = "/index.html"
status = 200

# Handle SPA routing
[[redirects]]
from = "/login"
to = "/index.html"
status = 200

[[redirects]]
from = "/register"
to = "/index.html"
status = 200

[[redirects]]
from = "/levels"
to = "/index.html"
status = 200

[[redirects]]
from = "/chat/*"
to = "/index.html"
status = 200

# Catch all other routes
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { REACT_APP_API_URL = "https://marketplace-api.eba-hekvtpzv.us-east-2.elasticbeanstalk.com" }