name = "ai-marketplace"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm install && npm run build"
publish = "frontend/build"

[site]
bucket = "./frontend/build"

# Routes for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { VITE_API_URL = "http://marketplace-api.eba-hekvtpzv.us-east-2.elasticbeanstalk.com" }